---
- name: system packages | remove nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: absent
  when: nginx_remove

- name: system packages | install nginx
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: nginx
    state: present

- name: nginx | remove default config
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
